namespace Compiler.InsertActionsInSyntax.ASTNodes.Enums
{
    public enum NodeType
    {
        PlusNode,
        BinaryMinusNode,
        UnaryMinusNode,
        MultipleNode,
        DivisionNode,
        Leaf,
        DefineNewType,
        Equality,
        Print,
        Println,
        NotEqual,
        MoreEqual,
        LessEqual,
        Equal,
        Less,
        More,
        LogicNot,
        LogicAnd,
        LogicOr,
        IfTerm,
        IfThenBegin,
        IfThenEnd,
        IfElseBegin,
        IfElseEnd,
        WhileTerm,
        WhileEnd,
        Read
    }
}
